SET SCHEMA APP;

DROP TABLE USERS;

CREATE TABLE USERS (USER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
			NAME VARCHAR(20) NOT NULL, 
			USERNAME VARCHAR(30) NOT NULL, 
			PASSWORD VARCHAR(16) NOT NULL, 
			EMAIL VARCHAR(80) NOT NULL,
			COMMUNITY_ID INTEGER NOT NULL);

INSERT INTO USERS (NAME, USERNAME, PASSWORD, EMAIL, COMMUNITY_ID) VALUES ('Paul', 'bassmonty', 'hisson', 'pmontoro88@gmail.com', 1);
INSERT INTO USERS (NAME, USERNAME, PASSWORD, EMAIL, COMMUNITY_ID) VALUES ('Jake', 'jdro', 'abc', 'jake@treblesandclefs.com', 2);
INSERT INTO USERS (NAME, USERNAME, PASSWORD, EMAIL, COMMUNITY_ID) VALUES ('Norman', 'normrich', 'abc', 'norman.richards@acc.edu', 2);
INSERT INTO USERS (NAME, USERNAME, PASSWORD, EMAIL, COMMUNITY_ID) VALUES ('Shindhu', 'shindhu', 'abc', 'shindhu@gmail.com', 3);
INSERT INTO USERS (NAME, USERNAME, PASSWORD, EMAIL, COMMUNITY_ID) VALUES ('Chris', 'mccarron', 'abc', 'chris.mccarron@msn.com', 1);
INSERT INTO USERS (NAME, USERNAME, PASSWORD, EMAIL, COMMUNITY_ID) VALUES ('Kelly', 'keene', 'abc', 'keene@yahoo.com', 1);
INSERT INTO USERS (NAME, USERNAME, PASSWORD, EMAIL, COMMUNITY_ID) VALUES ('Justin', 'justincasey', 'abc', 'justins@att.net', 1);

SELECT * FROM USERS;

SELECT USERS.USER_ID, USERS.NAME, USERS.USERNAME, USERS.EMAIL, COMMUNITYLIST.NAME
FROM USERS
INNER JOIN COMMUNITYLIST
ON COMMUNITYLIST.COMMUNITY_ID=USERS.COMMUNITY_ID;

SELECT * FROM USERS WHERE ID = 5;
SELECT * FROM USERS WHERE NAME='Paul Montoro';


						
SELECT USERS.USER_ID, USERS.NAME, USERS.USERNAME, USERS.EMAIL, COMMUNITYLIST.NAME FROM USERS INNER JOIN COMMUNITYLIST ON COMMUNITYLIST.COMMUNITY_ID=USERS.COMMUNITY_ID ORDER BY USER_ID;

